"""empty message

Revision ID: a3cd4114f1d8
Revises: 3c194001d0d7
Create Date: 2018-05-23 12:13:44.419829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3cd4114f1d8'
down_revision = '3c194001d0d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feed', 'title')
    # ### end Alembic commands ###
